version: '2'

services:
  puppet:
    container_name: puppet
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - 8140:8140
    volumes:
      - ./code:/etc/puppetlabs/code/
      - /etc/puppetlabs/puppet/ssl/
      - /opt/puppetlabs/server/data/puppetserver/
    dns_search:
      - .

  puppetdbpostgres:
    container_name: postgres
    image: puppet/puppetdb-postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data/
    dns_search:
      - .

  puppetdb:
    hostname: puppetdb
    image: puppet/puppetdb
    ports:
      - 8080
      - 8081
    volumes:
      - /etc/puppetlabs/puppet/ssl/
    dns_search:
      - .

  puppetboard:
    image: puppet/puppetboard
    ports:
      - 8000
    dns_search:
      - .

  puppetexplorer:
    image: puppet/puppetexplorer
    ports:
      - 80
    read_only: true
    dns_search:
      - .
